### ISSUE TITLE
Replace Paranoia with Discard

### ISSUE THREAD

**Issue by rosle** [nimblehq/rails-templates#103]
@olivierobert found that the `Paranoia` is being replaced by [Discard](https://github.com/jhawthorn/discard) gem

Why should we use `Discard` 
- https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid

We would need to evaluate what to change and how it works. The difference that we notice is on `Discard`, it does not apply the default scope which means `.all` returns both `kept` and `discarded`. And we would need to check more on how `dependent: destroy` works.

**Comment by ankitkalia1195** [comment]
@rosle Closing this as in  https://github.com/nimblehq/rails-templates/pull/296 we merged discard gem.
