### ISSUE TITLE
Remove Turbolinks-related data attributes in the layout

### ISSUE THREAD

**Issue by rosle** [nimblehq/rails-templates#104]
As currently we're not including the turbolinks in the project by default. We've already removed turbolinks in gemfile and javascript. But in the layout, there are still turbolinks-related attributes.

```
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
```

We should remove those too.

**Comment by svnlto** [comment]
According to the docs, this can be achieved with the `--skip-turbolinks` flag.

**Comment by rosle** [comment]
I recheck this one and seems it does not generate this anymore.

This is the layout generated
```
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
```

I think I'm going to close this for now.
