### ISSUE TITLE
Tidy up logging

### ISSUE THREAD

**Issue by svnlto** [nimblehq/rails-templates#109]
https://github.com/roidrage/lograge

Instead of having an unparsable amount of logging output like this:

```sh
Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100
Processing by HomeController#index as HTML
  Rendered text template within layouts/application (0.0ms)
  Rendered layouts/_assets.html.erb (2.0ms)
  Rendered layouts/_top.html.erb (2.6ms)
  Rendered layouts/_about.html.erb (0.3ms)
  Rendered layouts/_google_analytics.html.erb (0.4ms)
Completed 200 OK in 79ms (Views: 78.8ms | ActiveRecord: 0.0ms)
```

you get a single line with all the important information, like this:

```sh
method=GET path=/jobs/833552.json format=json controller=JobsController  action=show status=200 duration=58.33 view=40.43 db=15.26
```

**Comment by malparty** [comment]
We will test the gem for a few weeks in our current project, it the experience brings some benefits, I will add it to the template. If not, or if any issue if found, I will close the issue 😇

**Comment by malparty** [comment]
No problem so far, I did not miss any logs either. I will prioritize the story then 🚀
