### ISSUE TITLE
Code alignment

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#112]
The current Rubocop configuration prefer this style

![image](https://user-images.githubusercontent.com/11751745/59251386-e1cd1980-8c53-11e9-8c27-4feb92cf3282.png)

For me, I think it's nicer if we change the Rubocop configuration to support this style **(aligned hash key, has value, aligned the equal)**

![Pasted_Image_6_11_19__14_19](https://user-images.githubusercontent.com/11751745/59251439-02956f00-8c54-11e9-98a4-029609e32489.png)

To change that, we need to update the [RuboCop/Cop/Layout/AlignHash](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/AlignHash) in the `rubocop.yml` file.

![image](https://user-images.githubusercontent.com/11751745/59251245-8ef36200-8c53-11e9-9a71-47380bb4a926.png)

And update the [RuboCop/Cop/Layout/ExtraSpacing](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/ExtraSpacing) in the `rubocop.yml` file.

![image](https://user-images.githubusercontent.com/11751745/59253678-f4961d00-8c58-11e9-99a4-582feb9695de.png)

To format the code, we can use the Rubocop autocorrect feature `rubocop -a` 

If we prefer the new style, I will open a PR to update the Rails template also open a PR to update the convention on Compass.

**Comment by olivierobert** [comment]
If it's done automatically then that's fine e.g. using Rubocop autocorrect with a pre-commit (`rubocop -a`) or Prettier. But without it, it's annoying to maintain such alignment by hand

**Comment by anduonghien** [comment]
It can be done via Rubocop autocorrect @olivierobert

**Comment by andyduong1920** [comment]
Close that issue not only because of the vote result, it’s also that feature doesn’t strong enough to be the template, it’s a small thing and depends on each project. Each project could custom if needed.
