### ISSUE TITLE
Replace SCSS-Lint by Stylelint

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/rails-templates#115]
In order to make styling more agnostic (SCSS, Sass, Les), we could check is it would be good to move to https://stylelint.io/

Here is the plugin for Pronto: https://github.com/kevinjalbert/pronto-stylelint.

**Comment by rosle** [comment]
We are now moved to stylelint. But haven't set up the danger to report the feedback.

**Comment by rosle** [comment]
As of now, we don't have any stylelint report on the PR yet even when we migrate from pronto to danger. I'll create a new issue to integrate danger for stylelint (Maybe in the next minor version), So we can close this one 🙇

**Comment by rosle** [comment]
New Issue for integrate danger stylelint - https://github.com/nimblehq/rails-templates/issues/323. I'll now close this 🙏
