### ISSUE TITLE
Should we add the scsslint and eslint to the codebase_spec.rb

### ISSUE THREAD

**Issue by anduonghien** [nimblehq/rails-templates#121]
## Issue

As we have SCSS linte and ES linter, and we check that manually, it works but sometimes we forgot to run it and because there is no test for that, so the invalid code can go to production 😱  we should add it to the **codebase_spec.rb**

```
  it 'does not offend scsslint' do
    expect(`scss-lint .`).to be_empty
  end

  it 'does not offend eslint' do
    expect(`yarn run eslint .`).to include 'Done'
  end
```

Then we can get something like this

![image](https://user-images.githubusercontent.com/11751745/66466158-6c137600-eaac-11e9-84ef-ebc90f97ba2c.png)

## Vote

[![](https://api.gh-polls.com/poll/01DPQWDVQC3TYY9M3T4SM0ZATH/Yes%2C%20we%20should%20run%20it%20automatically)](https://api.gh-polls.com/poll/01DPQWDVQC3TYY9M3T4SM0ZATH/Yes%2C%20we%20should%20run%20it%20automatically/vote)
[![](https://api.gh-polls.com/poll/01DPQWDVQC3TYY9M3T4SM0ZATH/No%2C%20we%20can%20run%20it%20manually)](https://api.gh-polls.com/poll/01DPQWDVQC3TYY9M3T4SM0ZATH/No%2C%20we%20can%20run%20it%20manually/vote)

**Comment by olivierobert** [comment]
@anduonghien do a vote to get fast feedback :-) 

We usually use https://gh-polls.com/

**Comment by anduonghien** [comment]
@olivierobert Will create the pool later, for now just notice some stuff that we can improve in our template first.

**Comment by anduonghien** [comment]
Created the poll @olivierobert

**Comment by anduonghien** [comment]
This is done in 93e2ac7c37df76b0b0480de421250765c67f02b3
