### ISSUE TITLE
Adding livingstyleguide 

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#128]
As we use the [livingstyleguide](https://github.com/livingstyleguide/livingstyleguide) on most of the project, should we add this to the template

[![](https://api.gh-polls.com/poll/01DQY8XWS7W24H5DZRFR2WZZ36/Yes)](https://api.gh-polls.com/poll/01DQY8XWS7W24H5DZRFR2WZZ36/Yes/vote)
[![](https://api.gh-polls.com/poll/01DQY8XWS7W24H5DZRFR2WZZ36/No)](https://api.gh-polls.com/poll/01DQY8XWS7W24H5DZRFR2WZZ36/No/vote)

**Comment by malparty** [comment]
As [livingstyleguide](https://github.com/livingstyleguide/livingstyleguide) is no longer maintained, I will close this issue. 
Tho @andyduong1920 feel free to create a new issue to "search" for an alternative 🙇

**Comment by andyduong1920** [comment]
Yeah, thanks @malparty 👍
