### ISSUE TITLE
Change the default cassette record mode to `once`

### ISSUE THREAD

**Issue by longnd** [nimblehq/rails-templates#131]
The current default cassette [record mode](https://relishapp.com/vcr/vcr/v/5-0-0/docs/record-modes) is: `none` (see: [support/vcr.rb](https://github.com/nimblehq/rails-templates/blob/master/shared/rspec/support/vcr.rb#L11)) which: 
> allows previously recorded responses to be replayed but raises an error for any new requests and no new HTTP requests will be made

I find it's annoying since I have to change this option every time I want to record a new response AND change it back to `none` but there were many times I forget to revert the change and mistakenly commit that file.

I think we should change the default option to: `once` ([document](https://relishapp.com/vcr/vcr/v/5-0-0/docs/record-modes/once)), which:
> Replay previously recorded interactions and record new interactions if there is no cassette file.

[another point of view](https://bitbucket.org/nimblehq/the1-api/pull-requests/105#comment-120691036) is:
> The upside of saibling recording is that left unchecked it forces dev to force it on purpose so they are aware that network requests are triggered. In terms of organization, it forces devs to name properly recordings. But the downside is that it’s manual to enable it.

so let's do a vote, which option do you prefer:
[![](https://api.gh-polls.com/poll/01DSA3ZXV35H554T7P5MD0Y9E9/once)](https://api.gh-polls.com/poll/01DSA3ZXV35H554T7P5MD0Y9E9/once/vote)
[![](https://api.gh-polls.com/poll/01DSA3ZXV35H554T7P5MD0Y9E9/none)](https://api.gh-polls.com/poll/01DSA3ZXV35H554T7P5MD0Y9E9/none/vote)

**Comment by olivierobert** [comment]
@longnd How about keeping to `none` in the config but instead document the use of RSpec metadata at the example level:

```ruby
describe "Using an options hash", vcr: { record: :once } do
  it 'uses the provided cassette name' do
    #...
  end
end
```

Official documentation 👉 https://relishapp.com/vcr/vcr/v/2-4-0/docs/test-frameworks/usage-with-rspec-metadata#pass-a-hash-to-set-the-cassette-options

**Comment by anduonghien** [comment]
setting as `one` could leak a case that we forgot to commit the `vcr` file and on CI it will do a real request without noticing us, so we don't know about that case and it keeps requesting to the external server.

But setting it as `none` if we don't commit the vcr file, on CI it will raise the error so we can fix that.

What do you think @longnd

**Comment by longnd** [comment]
> setting as `once` could leak a case that we forgot to commit the vcr 

I think it's a valid point @anduonghien. Besides that, the voting results show that there're more people prefer keeping the `once` option.

**Comment by anduonghien** [comment]
> > setting as `once` could leak a case that we forgot to commit the vcr
> 
> I think it's a valid point @anduonghien. Besides that, the voting results show that there're more people prefer keeping the `none` option.

Thanks @longnd I think we can close this issue for now :)
