### ISSUE TITLE
Improving Rails boot time with Zeus

### ISSUE THREAD

**Issue by namtx** [nimblehq/rails-templates#135]
How about adding [Zeus](https://github.com/burke/zeus) to preload Rails app so it improves Rails boot time.

**Comment by namtx** [comment]
Additional link: https://thoughtbot.com/blog/improving-rails-boot-time-with-zeus

**Comment by anduonghien** [comment]
IMO As we have [bootsnap](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#bootsnap) that come by default from Rails 5.2 and Zeus is not maintenance by the community over 2 years so I think we don't need Zeus anymore :)

**Comment by namtx** [comment]
yeah, I think it can be used for personal purpose, instead of integrating it into rails template.
