### ISSUE TITLE
Add `sanitize` helper in the spec

### ISSUE THREAD

**Issue by junan** [nimblehq/rails-templates#141]
**Why**

In the system test,  we need to match content with translated text like
```ruby
 expect(page).to have_content I18n.t('campaign.description')
```

But if the translation text is a html like `I18n.t('campaign.description_html')`
we have to do `sanitize` it like

```ruby
expect(page).to have_content  ActionView::Base.full_sanitizer.sanitize I18n.t('campaign.description_html ')
```

Which gets longer the line and not very readable

If we define the `senitize` method like in the spec helper like
```ruby
def sanitize(html)
  ActionView::Base.full_sanitizer.sanitize(html)
end

```

We can test it like

```ruby
expect(page).to have_content sanitize 18n.t('campaign.description_html')
```

Which is more cleaner.

**Comment by anduonghien** [comment]
Resolved in https://github.com/nimblehq/rails-templates/pull/143
