### ISSUE TITLE
Update nimble branding from `nimbl3` to `nimblehq`

### ISSUE THREAD

**Issue by rosle** [nimblehq/rails-templates#169]
1. The screenshot bucket should be renamed

2. Our eslint package needs to be renamed - This will be related with another repo - `@nimbl3/eslint-config-nimbl3`

**Comment by olivierobert** [comment]
eslint package name updated in #184

**Comment by anduonghien** [comment]
> eslint package name updated in #184

This issue is solved in #184 and 45e4b424108763e1cad6e1a433f91df0abc8c32c
