### ISSUE TITLE
Migrating From Sprockets to Webpacker

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/rails-templates#194]
As we're using Rails 6 that shipped the `webpacker` by default, so we can migrate to use webpacker as assets compiler

## What to do

*We can follow [this guide](https://blog.carbonfive.com/migrating-from-sprockets-to-webpacker/):*

- Move the content in assets folder to javascript folder
- Import `application.css` in JS
- Use new helper `stylesheet_pack_tag` instead of `stylesheet_link_tag`
- Use new helper for images: `image_pack_tag` instead of `image_tag`
- We can enable SplitChunks plugin
- Remove the dependencies that are no longer needed

## Who Benefits

Web chapter

**Comment by ankitkalia1195** [comment]
@malparty Would you be interested to work on this one?

**Comment by andyduong1920** [comment]
As I remember @hoangmirs had some issues with the `Non-Sprocket` config 🤔

**Comment by malparty** [comment]
@ankitkalia1195 why not! It could be a good learning for next week (if no other plan than nice-to-have from the IC) :)

**Comment by malparty** [comment]
> @ankitkalia1195 why not! It could be a good learning for next week (if no other plan than nice-to-have from the IC) :)
> **Update:** I've assigned myself, I will give it a try on spare time~

After some review, I might prefer to focus on other parts at the moment. Webpacker does not seems to be the future for Rails so I'm not sure if we should really invest effort in that direction~

**Comment by ankitkalia1195** [comment]
@andyduong1920 @hoangmirs How do you guys think about comment from @malparty , can we close this issue if its not worth it?

**Comment by rosle** [comment]
I think we can close this now as with Rails 7, we now moving away from webpacker back to the sprockets due to the new Rails way to manage assets. I'll close this issue once we have [the PR](https://github.com/nimblehq/rails-templates/pull/315) merged.
