### ISSUE TITLE
Change default configs in test env

### ISSUE THREAD

**Issue by abhinavmsra** [nimblehq/rails-templates#20]
1. Enable `eager_load` of classes.

2. Enable `Bullet` errors to indicate N+1 queries.

**Comment by rosle** [comment]
@abhinavmsra I created a pr for enabling the Bullet 👍. But for enabling `eager_load` on test. I am not sure. What is the reason behind it?

**Comment by anduonghien** [comment]
This is in the default **test.rb** file generated by Rails, I think we could keep it like that as default, we could turn it on in the specific project if needed @abhinavmsra @rosle 

![image](https://user-images.githubusercontent.com/11751745/90375707-868c8780-e09f-11ea-8fae-0af5599f297e.png)

**Comment by andyduong1920** [comment]
Closing as the template has **bundle exec rake zeitwerk:check** in [codebase_spec.rb](https://github.com/nimblehq/rails-templates/blob/develop/spec/codebase/codebase_spec.rb#L13) and it covers the eager load issue already
