### ISSUE TITLE
Slim addon

### ISSUE THREAD

**Issue by rafayetn** [nimblehq/rails-templates#213]
As proposed by @anduonghien [in this link](https://github.com/nimblehq/rails-templates/pull/195#discussion_r471920200) and we use slim template engine for our projects we can make it default in our template.

- [x] Add Slim addon
- [x] Add slim-lint to danger system

**Comment by byhbt** [comment]
hi @rafayetn and @anduonghien 

IMO, Slim is quite good but I think the template engine depends on the project and personal/team preferences.
The `rails-templates` is an open-source project not for only our company but also for the community.
 
Should we make `slim` as default for our template?

**Comment by anduonghien** [comment]
Yeah good point @byhbt, we can set it as an option, addon, so during the generate step we could ask the user that `Do you want to use slim template` -> If the user chooses Yes -> then we add it.
