### ISSUE TITLE
Use danger-simplecov_json

### ISSUE THREAD

**Issue by neua-wd** [nimblehq/rails-templates#221]
[danger-simplecov_json](https://github.com/marcelofabri/danger-simplecov_json) is a plugin for [danger](https://github.com/danger/danger). It provides the test suite code coverage report as a comment in each PR.

Implemented on The1
![Screen Shot 2563-09-09 at 16 03 57](https://user-images.githubusercontent.com/60864585/92578466-12b45800-f2b6-11ea-9cd5-5b451d59dd64.png)

## What to do

- Implement the mentioned gem (following the implementation on The1 project)

## Who Benefits

- Web chapter
- Test suite quality

**Comment by olivierobert** [comment]
@neua-wd Does this link to the actual output of the code coverage to see the details? If not, it would be a good addition and it would require to use Semaphore or Github actions artefacts 💭

**Comment by neua-wd** [comment]
@olivierobert It only displays the percentage without a link to the details. That would be a good addition 👍 , I'll look into it 😃

**Comment by olivierobert** [comment]
@neua-wd @andyduong1920 There is also https://github.com/grodowski/undercover to report warnings of classes/modules requiring additional test coverage. So maybe instead of linking to the code coverage reports (which contain the data for low coverage), we could get the warnings as comments 💭

**Comment by andyduong1920** [comment]
Well, display the details would be great, but it looks like we need to find a better way for that, like upload the details (by using Semaphore/Github Action artifact), there is something we need to check like

- Where should we upload that report? (eg: S3, Github host, ....)
- How to link that back to the Pull request
- Do we need to care about the privacy, let say Do we need that file public on the Internet, anyone could see that and saw that report (think about the private client project) 🤔
- ...

So with all of that, I would like to separate it to another PR, so Neua can implement this issue first to have this feature and will display the details on a separate PR, what do you think @olivierober cc @neua-wd

**Comment by olivierobert** [comment]
@andyduong1920 @neua-wd  I agree that seeing the details can be done in another PR and efforts.

In terms of privacy, storing as artifact in the CI would be the best.
