### ISSUE TITLE
Replace the `figaro` gem to `dotenv-rails` gem

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#23]
The problem is we want to share the ENV variable between Rails and Node JS on the development environment.

For Rails, the `figaro` use the `application.yml` to export the ENV variables.

For Node JS, we use the [dotenv](https://github.com/motdotla/dotenv) to load the ENV on development environment, the ENV variables store in `.env` file.

So the problem now is we have 2 places to store the ENV variable for the development environment, 1 is `application.yml` for Rails and 1 is `.env` for Node JS.

So on Rails, if we change the Gem from `figaro` to [dotenv-rails](https://github.com/bkeepers/dotenv), we can use the same `.env` file both Rails and Node JS.

**Comment by MidnightWonderer** [comment]
I prefer the docker-compose way and removing both gems altogether.  
Just my 2 cents anyway.

**Comment by abhinavmsra** [comment]
@MidnightWonderer we could use that when we deploy docker containers, which we dont yet.

**Comment by olivierobert** [comment]
@anduonghien way back, we used to rely on dotenv but moved to Figaro as it has better support for Heroku + we can group/share variables for all environment in a single file vs multiple files with dotenv. 

As for sharing env variables between Ruby and JS, it's not a critical issue in our current setup as we usually have a JS to a front-end client (not a Node.JS app) which is not sharing much dependency with the Ruby backend.

But if we find it's something we would like to have to be future-proof then I don't see any issue to switch back

**Comment by malparty** [comment]
Closed in favor of #394  (sorry for that duplicate 🙈 )
