### ISSUE TITLE
Sidekiq worker couldn't run on Heroku

### ISSUE THREAD

**Issue by gutakk** [nimblehq/rails-templates#260]
## Issue

Sidekiq worker couldn't run on Heroku as the command in `Dockerfile.worker` is `./bin/sidekiq.sh` but the `sidekiq.sh` file doesn't exist.
 
## Expected

Sidekiq worker can able to run on Heroku. In my opinion, there are 2 ways to solve this issue.
1. Create a `sidekiq.sh` file
2. Change the command in `Dockerfile.worker`
 
## Steps to reproduce

1. Create rails app using `rails-template`
2. Deploy to Heroku
3. Enable Sidekiq worker
4. Error will appear to the Heroku log

**Comment by andyduong1920** [comment]
I vote for the 2️⃣  solution @gutakk change the commend in `Dockerfile.worker` into `worker.sh` as `worker term` is generic than `sidekiq.sh` and because the filename is `Dockerfile.worker` so it does make sense the content also is `worker.sh`.
