### ISSUE TITLE
Update the README generated for new projects

### ISSUE THREAD

**Issue by bterone** [nimblehq/rails-templates#286]
## Issue

With the addition of the Github Wiki to projects, it no longer makes sense to frontload all the technical setup instructions on the README.

## Solution

Have the README serve a more introductory purpose to the project. Most examples of websites with READMEs have more user-friendly introductions to the project. 

⚠️ The new README is optional and is only generated if we choose to add the Github WIki into the project ⚠️ 

The proposed changes would be as follows:

**Current Template Headings**
- Introduction
- Project Setup
  - Prerequisites
  - Docker
  - Development
- Tests
  - Docker-based tests on the CI server
  - Semaphore CI 2.0
  - Github Actions
  - Test
- Automated Code Review Setup

**Proposed Headings**
- Introduction
- Documentation
  - Project Setup

_____
We will link the Documentation to the `Home` section of the Github Wiki, and the Project Setup to the `Getting Started` ✅ 
 
## Who Benefits?
Increases perceived value to future clients 💰 
 
## What's Next?
- [ ] Update the template README by introducing the new structure

Please comment if you have some sections that should be included in the new README 😄 
[![](https://api.gh-polls.com/poll/01F1YGTD2EX6081VA16KH0NPHN/Yeah%2C%20I%20like%20the%20new%20README)](https://api.gh-polls.com/poll/01F1YGTD2EX6081VA16KH0NPHN/Yeah%2C%20I%20like%20the%20new%20README/vote)
[![](https://api.gh-polls.com/poll/01F1YGTD2EX6081VA16KH0NPHN/No%2C%20I%20prefer%20the%20old%20README)](https://api.gh-polls.com/poll/01F1YGTD2EX6081VA16KH0NPHN/No%2C%20I%20prefer%20the%20old%20README/vote)

**Comment by andyduong1920** [comment]
@bterone  Some projects won't host on Github, so maybe we can make it optional, something like Would you like generating the Github Wiki.

**Comment by bterone** [comment]
> @bterone Some projects won't host on Github, so maybe we can make it optional, something like Would you like generating the Github Wiki.

That's a good point, if that's the case perhaps we could generate the updated README with the Github Wiki if they choose to use Github, how does that sound? 🤔  @andyduong1920

**Comment by andyduong1920** [comment]
> > @bterone Some projects won't host on Github, so maybe we can make it optional, something like Would you like generating the Github Wiki.
> 
> That's a good point, if that's the case perhaps we could generate the updated README with the Github Wiki if they choose to use Github, how does that sound? 🤔 @andyduong1920

Yeah sounds good @bterone, let add that to the Issue's description too, so we won't forget it later :)

**Comment by rosle** [comment]
@bterone @andyduong1920 Just merged the Github wiki, the changes are

- Github wiki is now an optional addon
- If the user selects the Github addon, the content in readme will be split to wiki pages

This is the generated wiki pages from the template:

```markdown
## Table of Contents

- [[Home]]
- [[Getting Started]]

## Architecture

- [[Authentication]]

## Infrastructure

- [[CI/CD|CI CD]]

## Operations

- [[Testing]]
```

I'm closing this now. If there are anything missing, feel free to reopen the issue 🙇
