### ISSUE TITLE
No new line generated at the end of `.rspec`, `Procfile`, `Procfile.dev` file 

### ISSUE THREAD

**Issue by junan** [nimblehq/rails-templates#292]
## Why

Currently, when we generate an app with this template, it does not add a new line at the end of `.rspec`, `Procfile`, `Procfile.dev` file. We need to update our template file so it add's a new line at the end of these files.

## Who Benefits?

Developers

**Comment by ankitkalia1195** [comment]
@junan Nice one, we can go ahead with it, you can open a PR whenever you have time 👍
