### ISSUE TITLE
Upgrade Ruby to 3.1.x

### ISSUE THREAD

**Issue by rosle** [nimblehq/rails-templates#316]
## Why

There is an attempt to upgrade it on https://github.com/nimblehq/rails-templates/pull/312

But there is an issue.

> /.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Unknown alias: default (Psych::BadAlias)

After investigation, I found it is from [figaro](https://github.com/laserlemon/figaro) gem.

```
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:60:in `parse'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:56:in `block in raw_configuration'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:56:in `raw_configuration'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:64:in `global_configuration'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:32:in `configuration'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:42:in `each'
from /.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/figaro-1.2.0/lib/figaro/application.rb:36:in `load'
```

This is because on Ruby 3.1.0, it comes with Psych 4 - https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

> Psych 4.0 changes Psych.load to use safe_load by default. You may need to use Psych 3.3.2 for migrating to this behavior. [[Bug #17866]](https://bugs.ruby-lang.org/issues/17866)

In the issue, they explained that now YML is loaded with `aliases: false` by default. So when the app tries to load Figaro's `config/application.yml`, it failed because in that file, we're using alias. To fix we need to pass `aliases: true` when [loading the config](https://github.com/laserlemon/figaro/blob/6ae998e8209a08f91a165822abecffc0a0626814/lib/figaro/application.rb#L60) just like they've done on [Rails](https://github.com/rails/rails/commit/179d0a1f474ada02e0030ac3bd062fc653765dbe). 

So in order to upgrade to Ruby 3.1, we need to have this issue fixed on figaro. I'll open the issue. But if no one responds, we will need to fork or look into other alternatives. 
 
## Who Benefits?

developers

**Comment by malparty** [comment]
@rosle I see that the Figaro gem did not get any update since 3 years. Shoud I create an issue about removing this gem from our template (and using `database.yml` and `.env` instead)? :) 

This would unlock the upgrade from Ruby 3.0 to 3.1 and maybe 3.2 🥳

**Comment by rosle** [comment]
> @rosle I see that the Figaro gem did not get any update since 3 years. Shoud I create an issue about removing this gem from our template (and using `database.yml` and `.env` instead)? :)
> 
> This would unlock the upgrade from Ruby 3.0 to 3.1 and maybe 3.2 🥳

Yeah 😂, Seems there won't be any new version released soon. I think maybe we can remove it for now to unblock this. And later we can introduce a new one maybe dotenv. 🙆‍♀️
