### ISSUE TITLE
Import bootstrap SCSS functions before variables in order to benefit from scss functions

### ISSUE THREAD

**Issue by malparty** [nimblehq/rails-templates#393]
## Why

Currently, we set variables like `2rem; // 32px`. Because the variables are imported before the `@import 'bootstrap/scss/functions';`. According to bootstrap documentation, we can import the variable overrides after it and use these functions :)

- https://getbootstrap.com/docs/5.2/migration/
- SASS doc from bootstrap https://getbootstrap.com/docs/5.3/customize/sass/#importing
- Suggestion by Olivier: https://github.com/nimblehq/rails-templates/pull/390#discussion_r1107929525
 
## Who Benefits?

Developers when codding the scss variables.

**Comment by andyduong1920** [comment]
Hi @malparty not sure [this PR](https://github.com/nimblehq/rails-templates/pull/439/files) could solve this issue

**Comment by malparty** [comment]
> not sure [this PR](https://github.com/nimblehq/rails-templates/pull/439/files) could solve this issue

@andyduong1920 Yes, it does 🥳 Thanks!! :)
