### ISSUE TITLE
Fix: The test coverage does NOT show the correct statistics

### ISSUE THREAD

**Issue by sanG-github** [nimblehq/rails-templates#413]
## Issue

The code coverage always shows 0.00%, which means it does not reflect the real code coverage of the project. It was caused by the SimpleCov not starting before the Rails was loaded. 
- Sample Fix on [EwaPayroll](https://diffy.org/diff/114f610cff391)
- [Related issue](https://github.com/simplecov-ruby/simplecov/issues/77)

![image](https://github.com/nimblehq/rails-templates/assets/63148598/902b6296-2102-4906-b524-5f18db98a581)

## Expected

Show accurate statistics.
![image](https://github.com/nimblehq/rails-templates/assets/63148598/fc8b15f1-a0d3-434d-843f-3e3f4fde8ce5)

## Steps to reproduce

1. Generate the project from the template
2. Push the code to the remote repository
3. Add codes, and create a PR
4. 💥

**Comment by andyduong1920** [comment]
@htoo-eain-lwin as you had some work for this topic on your IC, you could colobrate with @sanG-github on this topic 👌

**Comment by sanG-github** [comment]
@htoo-eain-lwin 
If you're interested in this matter, I can re-assign it to you. 😉
By the way, I've attached a PR in the description that outlines two ways to address this issue. Feel free to take a look and refer to it.

**Comment by htoo-eain-lwin** [comment]
Hello @sanG-github ,
Thanks for the consideration. Although, I am interested, I am currently busy with CX. 😅  
And I don't have access on the [EwaPayroll](https://github.com/onward-venture/ewa-payroll-web/pull/907).

**Comment by sanG-github** [comment]
Thank @htoo-eain-lwin. 😜 

I've updated the sample fix, please take a look at it again. Also, thanks for noticing, I will take care of resolving the issue myself.  🙏
