### ISSUE TITLE
Enable source-map option in CSS build

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#414]
## Why

As we build the CSS with `no-source-map` option, the `source-map` it could help to debug the issue. 

Related discussion: https://github.com/nimblehq/rails-templates/pull/405/files#r1232024858

## Who Benefits?

Developer

**Comment by mosharaf13** [comment]
If source-map is enabled with `embed-sources` key, it points to correct `.scss`. Only downside is that it will generate large map files as mentioned [here](https://sass-lang.com/documentation/cli/dart-sass/#embed-sources)


Enabling source-map without embedding sources tries to point at .scss files by relative path, and as that path is not publicly accessible, it returns 404. 


Should `build:css` be changed like below?


```
    "build:css": "sass app/assets/stylesheets/application.scss app/assets/builds/application.css --embed-sources --load-path=node_modules"

```
@malparty @tyrro

**Comment by tyrro** [comment]
@mosharaf13 , that's interesting, could you compare these three options in terms of the bundled size? I am curious to see how these three options affect the final bundle size.

--no-source-map(current) | --embed-sources | --source-map-urls=absolute
-|-|--
`du -sh app/assets/builds` returns: | `du -sh app/assets/builds` returns: | `du -sh app/assets/builds` returns:

**Comment by tyrro** [comment]
Thanks for the results!
It seems  `--source-map-urls=absolute` doesn't make any increase in the final bundled size, so we can go with that one! Great!
