### ISSUE TITLE
Upgrade Node version to 18

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#421]
## Why

As 18 is the latest Node LTS version. There is 2 blockers in upgrade to Node 18

>  @nimblehq/stylelint-config-nimble

=> This is now fixed and this issue is unlocked! 🚀 

> @nimblehq/eslint-config-nimble

=> This is not fixed yet ❌ https://github.com/nimblehq/eslint-config-nimble/issues/56

## Who Benefits?

Developers

```[tasklist]
### Tasks
```

**Comment by mosharaf13** [comment]
Hi @andyduong1920 ,

`@nimblehq/eslint-config-nimble` version `2.4.0` doesn't support node 18. It seems [here](https://github.com/nimblehq/eslint-config-nimble/releases) that supporting version `2.6.0` has been released in github, but it isn't available in [npm registry](https://www.npmjs.com/package/@nimblehq/eslint-config-nimble?activeTab=versions).

Looking for your suggestion about the way forward.

**Comment by andyduong1920** [comment]
@mosharaf13 could you reach out to @carryall as she is the maintainer for these packages 🙏

**Comment by andyduong1920** [comment]
And also, to be clear, I do not `=> This is now fixed and this issue is unlocked! 🚀` :D because I don't know the state of the `[@nimblehq/stylelint-config-nimble](https://github.com/nimblehq/stylelint-config-nimble)` :D I just now that we can't use Node 18 at this moment hehe

![image](https://github.com/nimblehq/rails-templates/assets/11751745/3363951c-b1a2-4e75-b8d0-d7a38e94267b)

So the way to go is double check with the Javascript guild (@carryall) For this topic over [Slack #js-guild](https://nimble-co.slack.com/archives/C01GL6RBW11) channel @mosharaf13

**Comment by malparty** [comment]
@andyduong1920 wasn't this fixed by https://github.com/nimblehq/stylelint-config-nimble/pull/13 ? 👀

**Comment by andyduong1920** [comment]
> @andyduong1920 wasn't this fixed by [nimblehq/stylelint-config-nimble#13](https://github.com/nimblehq/stylelint-config-nimble/pull/13) ? 👀

I'm not sure @malparty, could you check the status with @carryall or @hoangmirs

**Comment by hoangmirs** [comment]
@malparty @andyduong1920 Yeah, it was released in [1.0.3](https://github.com/nimblehq/stylelint-config-nimble/releases/tag/1.0.3)
So you can upgrade that dependency to continue on this issue 🎉

**Comment by andyduong1920** [comment]
> @malparty @andyduong1920 Yeah, it was released in [1.0.3](https://github.com/nimblehq/stylelint-config-nimble/releases/tag/1.0.3) So you can upgrade that dependency to continue on this issue 🎉

I doubt that is not actually ready @hoangmirs https://nimble-co.slack.com/archives/C01GL6RBW11/p1690427376112969?thread_ts=1689327996.399969&cid=C01GL6RBW11

**Comment by andyduong1920** [comment]
@hoangmirs @malparty I have updated the ticket description to make it clear, we have 2 blockers actually, one was fixed and another one is still there, that why we can't upgrade the Rails template to Node 18 yet ;) 

![image](https://github.com/nimblehq/rails-templates/assets/11751745/71d7fec2-8c15-4cee-ab90-0df8da96da1e)

**Comment by malparty** [comment]
@andyduong1920 I just realized #490 resolved this issue 🥳 🥳 🥳
