### ISSUE TITLE
Add svgeez addon

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#425]
## Why

As we use the https://github.com/jgarber623/svgeez for most of web project

## Who Benefits?

Developers

```[tasklist]
### Tasks
```

**Comment by tyrro** [comment]
@malparty , I am wondering whether you meant to mention [svgeez](https://github.com/jgarber623/svgeez/) because that's the one we use mostly(for example Flexi, CX Web), no? 🤔

**Comment by malparty** [comment]
> I am wondering whether you meant to mention [svgeez](https://github.com/jgarber623/svgeez/) because that's the one we use mostly(for example Flexi, CX Web), no? 🤔 [@tyrro]

We should ask @andyduong1920 🙈

**Comment by andyduong1920** [comment]
@tyrro @malparty Sorry, in CX we use svgeez 👍

**Comment by andyduong1920** [comment]
I updated the issue content to https://github.com/jgarber623/svgeez FYI @tyrro

**Comment by malparty** [comment]
Nice catch @tyrro !!!
