### ISSUE TITLE
Revisit the test workflow 

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/rails-templates#429]
## Why

Need to double check [this value ](https://github.com/nimblehq/rails-templates/blob/develop/.template/addons/github/.github/workflows/test.yml.tt#L46C71-L46C71)should be `develop` or `development`

<img width="802" alt="image" src="https://github.com/nimblehq/rails-templates/assets/11751745/5361fdb4-5f90-4406-8043-e9b903bcc95d">

## Who Benefits?

Developers

**Comment by sanG-github** [comment]
Based on the current implementation of the [branch-tag-action](https://github.com/nimblehq/branch-tag-action/blob/main/entrypoint.sh) workflow, it should be `develop` instead of ~`development`~ since the `BRANCH_TAG` depends on the `branch` or `tag`.
