### ISSUE TITLE
Remove unexpected_input being passed to actions/download-artifact@v3

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/rails-templates#447]
## Why

On the generated project, when [test.yml](https://github.com/nimblehq/rails-templates/blob/613e39ba9f7c89878405eedddcfaa6ce6bbeb183/.template/addons/github/.github/workflows/test.yml.tt#L143) runs at step `Run Danger`, we can see a warning as the following screenshot:

![image](https://github.com/nimblehq/rails-templates/assets/17830319/4b0ddf8a-3999-4247-b8fc-c3379e743a3f)

The warning says we are passing unexpected inputs to the download artifact. In our codebase, we are passing three such inputs - `github_token`, `workflow`, and `workflow_conclusion` in the following [lines](https://github.com/nimblehq/rails-templates/blob/develop/.template/addons/github/.github/workflows/test.yml.tt#L156-L158).

In order to avoid warnings caused by these unexpected inputs, we can remove them.

## Who Benefits?

@nimblehq/web-chapter

**Comment by Goose97** [comment]
+1 on this warning

In my case, the step also errors with this:
<img width="920" alt="image" src="https://github.com/nimblehq/rails-templates/assets/35915460/033e500d-ee57-4268-b5cf-5d93ef054dc9">

My guess is:
1. On the first run, we don't have any test cases, so no coverage info is generated. I tested again in my local machine, the behavior is the same
2. [The upload step](https://github.com/nimblehq/rails-templates/blob/develop/.template/addons/github/.github/workflows/test.yml.tt#L103-L107) finds no files and moves on
3. There's no files to download --> it errors
