### ISSUE TITLE
Fix: error when running Danger step in CI workflow

### ISSUE THREAD

**Issue by Goose97** [nimblehq/rails-templates#448]
## Issue

Upon running Github CI on my new Rails project, [the Danger step](https://github.com/nimblehq/rails-templates/blob/develop/.template/addons/github/.github/workflows/test.yml.tt#L189-L190) fails with [this error](https://github.com/Goose97/google-scraper-ruby/actions/runs/5663720608/job/15345930084)

I've tested again in my local setup, the behavior is the same the full error snippet is here: [run_danger_error.txt](https://github.com/nimblehq/rails-templates/files/12167644/run_danger_error.txt)

## Expected

The Danger step should finish without any error

## Steps to reproduce

1. Create a new project with these presets:
  - Github Actions + Wiki
  - Bootstrap
2. Open a PR to trigger the CI

**Comment by htoo-eain-lwin** [comment]
Hello @Goose97 , For now, I can bypass by using `brakeman.run('./')` or `brakeman.run('.')`. 
I will create a PR to hear insights from our colleagues too. :D

**Comment by Goose97** [comment]
Thank you for looking at this. Just figure out the same fix as well (should've notice the Github notifications 😢 ). I'll leave the issue I created here in for more context https://github.com/klaxit/danger-brakeman_scanner/issues/2
