### ISSUE TITLE
Move user_email in publish_wiki workflow to a secret

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/rails-templates#461]
## Why

- Currently, we are putting the user_email into the workflow with plain text.
- As this is a part of credentials, we should create a secret for it:
https://github.com/nimblehq/rails-templates/blob/26835203353ef6fc0ccf2ee079c010d17c6ab8ff/.template/addons/github/.github/workflows/publish_wiki.yml.tt#L30
- `user_email` should be put in the secrets like the `user_access_token`

## Who Benefits?

Developers

**Comment by sanG-github** [comment]
Closed this PR since the change is against [this RFC](https://github.com/nimblehq/compass/discussions/1334).

[Hoang's suggestion](https://github.com/nimblehq/rails-templates/pull/497#issuecomment-1874968045) would change that to use the new version of the action.
