### ISSUE TITLE
Remove the master branch out of some workflows

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/rails-templates#462]
## Why

As we're changing to using the `main` branch instead of `master`, we should update our workflows not to use the `master` branch anymore.
![image](https://github.com/nimblehq/rails-templates/assets/7344405/b1eb66e6-1733-4f5a-85e4-18ebd78c36cb)

## Who Benefits?

Developers

**Comment by sanG-github** [comment]
Closing this issue as it has already been resolved and deleted in #417. 🎉
