### ISSUE TITLE
Fix: Deprecation of the script to install NodeJS & Yarn from nodesource

### ISSUE THREAD

**Issue by longnd** [nimblehq/rails-templates#476]
## Issue
The script to install nodejs & yarn from nodesource is deprecated. Besides that, it is causing the build step for a minute to ensure the users are aware of the warning
https://github.com/nimblehq/rails-templates/blob/8714368cbcb42a0a4960787a654958f08b0a62b1/.template/addons/docker/Dockerfile.tt#L35-L46
![image](https://github.com/nimblehq/rails-templates/assets/1896814/4c2ece66-d5df-4260-9880-6e94195868ca)

## Expected
The step to install nodejs & yarn from nodesource should go well, without any warning.

## Steps to reproduce
- Generate a new project from the Rails template
- Build a new Docker image from the dockerfile
- Check the build log to see the warnings

**Comment by olivierobert** [comment]
FYI: I have pushed a fix in https://github.com/nimblehq/compass/pull/1358
