### ISSUE TITLE
Fix: Duplicated `Dockerfile` and `.dockerignore` when generating the project with Rails 7.1

### ISSUE THREAD

**Issue by sanG-github** [nimblehq/rails-templates#478]
## Issue

We're facing two duplicating errors when generating the project from our template that should be fixed ASAP👷‍ 

![image](https://github.com/nimblehq/rails-templates/assets/63148598/2f4c05f7-380e-4722-a934-01f689dbc67c)

## Expected

The template can generate a project successfully and there are no duplications or errors caused to the user

## Steps to reproduce

Both ways to generate the project faced the same issue.
```ruby
1. Run `rails new app_name -m https://raw.githubusercontent.com/nimblehq/rails-templates/main/template.rb` as documented.

Or

1. Clone our rails template locally
2. Run `rails new app_name -m ./template.rb`
```

**Comment by malparty** [comment]
It seems that it's a conflict between the Heroku and the Docker add-ons 🤔 Let me check that!

**Comment by malparty** [comment]
Can be fixed with simple 

```
remove_file 'Dockerfile'
remove_file '.dockerignore'
```

Later we might want to reuse these default dockerfiles but that's in `research` for the current sprint 👍
