### ISSUE TITLE
Create (or use) a Rubocop for the inverse keyword needed in the associations

### ISSUE THREAD

**Issue by Goose97** [nimblehq/rails-templates#494]
## Why

We have a comprehensive set of style guides in the Compass. Sometimes, it hard to keep them all of your head why developing. Turning it into a custom Rubocop rules can lower the cognitive overhead

- Implement (or use) a custom Rubocop to catch the missing `inverse` keyword in Rails associations

## Who Benefits?

Developers on standard admin projects.

**Comment by Goose97** [comment]
@malparty I found an existing [Rubocop rule](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsinverseof) that can achieve this. However, they seem more lax than our rule in Compass. This [invalid example](https://nimblehq.co/compass/development/code-conventions/ruby/ruby-on-rails/#convention-13) is considered valid according to their rule. It is because in this case, Rails can inferred the `inverse_of`.

So what should we do with this:
a) Use the existing Rails/InverseOf rule
b) If we prefer the explicit version, we can write a custom rule. The implementation is 80% finished (should've Google first 😅)

**Comment by malparty** [comment]
From my understanding, the existing cop is covering only the cases when the association is not a standard/default one, but 80% of our associations are standard ones (unless we use Rails engines, it's more around 60%). In either case, I think having a custom cop that requires the `inverse_of` explicit argument for ALL the associations might be preferable.

This answer assumes that the remaining 20% of work needed for the custom cop is not too hard of course, if there is any big blocker, we might want to consider (a).
