### ISSUE TITLE
Fix: The `./rubocop` folder is not copied to the generated project

### ISSUE THREAD

**Issue by malparty** [nimblehq/rails-templates#518]
## Issue

When a project is generated, the `./rubocop` folder is not generated.

There is an issue in `apply '.template/addons/custom_cops/template.rb'`.

## Expected

The `rubocop` folder must be copied to the generated root folder in order to run the custom cops.

## Steps to reproduce

1. Scaffold a new project
2. make dev
3. make codebase

**Comment by Goose97** [comment]
I will need some clarifications on this issue.

- I assume by scaffolding the project, you meant running this command?
```
rails new <project_name> -m https://raw.githubusercontent.com/nimblehq/rails-templates/main/template.rb
```

- On my side, the rubocop folder is copied successfully, but it fails with the `make codebase` command with this error
```
Error: Property AutoCorrect of cop FactoryBot/CreateList is supposed to be a boolean and contextual is not.
make: *** [codebase] Error 2
```

Is it the same situation with you? @malparty

**Comment by malparty** [comment]
@Goose97 Sorry for the confusion, on my previous tests, it did not even copy the `rubocop` folder, but now it's working. ><

![image](https://github.com/nimblehq/rails-templates/assets/77609814/16a6cee6-c6bc-4c72-ad5c-f1f7e4783bea)

Re-tested on branch `chore/update-dependencies-may-24`.


PS: when testing an app scaffolding, use `rails new NAME -m ../rails-templates/template.rb`. Where `../rails-templates` is the path to your local repository of the Rails Template. This way you are using the current branch you are working on. Using the URL will point to the `main` branch and might miss some features. 


I think we can close this issue 🤔
