### ISSUE TITLE
Configure `development.rb`to automatically generate the `translations` file

### ISSUE THREAD

**Issue by abhinavmsra** [nimblehq/rails-templates#6]
The translations file of `i18n-js` can be automatically generated by the `I18n::JS::Middleware`. 

To do that we need to add 
```
config.middleware.use I18n::JS::Middleware 
```
to our `config/environments/development.rb` file.

**Comment by rosle** [comment]
I checked but currently we did not add `i18n-js` gem in our template. Should we add it? @abhinavmsra @olivierobert
