### ISSUE TITLE
Change capybara default_max_wait_time back to default

### ISSUE THREAD

**Issue by fikrikarim** [nimblehq/rails-templates#63]
Right now the default Capybara default_max_wait_time on Rails template is 30s on local machine and 60s on CI. But is it the best setting? 🙈 

One example is from Braive. When we use Capybara.default_max_wait_time = 30s or 60s like from the Rails template, the Backend, Clinician and Page - System tests become around ~14min. This is much slower than the previous test, which had Capybara.default_max_wait_time = 5s, who have around ~7min testing time.

I think we have to keep the Capybara.default_max_wait_time = 5s or even 2s, like the default, because we already have retry system in place. And when looking at data from this and this, it seems some specs are still failing, even though we had wait for 60s:
![image](https://user-images.githubusercontent.com/13066728/44905367-16fb2180-ad3c-11e8-820e-10a871932853.png)
See this [PR's comment](https://bitbucket.org/nimbl3/braive-web/pull-requests/1048/159846848-dockerize-testing-environment/diff#comment-74635916) for link to the CI to see the build time.

In ideal world, Capybara shouldn't wait for anything. We already disable all animations when testing (at least on Braive), so Capybara isn't waiting for CSS animation. For waiting for AJAX request, better to use a wait_for_ajax helper:
```ruby
def wait_for_ajax
    Timeout.timeout(Capybara.default_max_wait_time) do
      loop until finished_all_ajax_requests?
    end
  end
```
And if we have to wait for something specific, we can use `:wait` option on each expectation:
```ruby
expect(page).to have_text('Lorem ipsum', wait: 3)
```

To be honest, I'm still not sure why some tests are failing randomly, and it isn't passed even when we had wait for 60s. But I think it's faster just to fail early, and make Rspec retry catch the failure and rerun the spec.

**Comment by fikrikarim** [comment]
Anyone has suggestion or insight?

**Comment by olivierobert** [comment]
@fikrikarim The config we have come from Gitlab. In an ideal world, there should not be any wait but CI environments can be unstable hence the need to account for that.
