### ISSUE TITLE
Rails 5.1.4 NOT support PG gem on version ~> 1.0.0

### ISSUE THREAD

**Issue by Yutna** [nimblehq/rails-templates#65]
We can NOT use the Rails generator to create the model since the Rails version 5.1.4 NOT support `pg` gem on version `1.0.0`.

We need to set the `pg` gem in Gemfile to something like this.

```ruby
gem 'pg', '~> 0.21.0'
```

**Comment by caherrerapa** [comment]
I think the issue is different. I use pg 1.0 regularly and faced this at some point but could fix it. Please consult with our teammates that are using Rails 5

**Comment by caherrerapa** [comment]
The issue is solved in Rails > 5.1.5
