### ISSUE TITLE
Add Basic Layouts for Devise's Auth Pages

### ISSUE THREAD

**Issue by julien731** [nimblehq/rails-templates#73]
We're using Devise for every project, and every time we're creating sign-in and sign-up pages that are quite similar in style.

In order to implement faster, we should have a basic layout defined in the template directly which could then be styled for each project.

**Comment by olivierobert** [comment]
Actually, the direction was to make more modular using mountable engines, hence https://github.com/burigems/buriauth.

So I am not in favor to add views templates as-is in the main Rails template. 

An option is to make this optional using branches (as per the Android template):

![branches_ _nimbl3_android-templates](https://user-images.githubusercontent.com/696529/48192996-f70b5e00-e37b-11e8-925b-eb92d3ad3b95.png)

So the flow, in this case, is to clone the main template and merge the extra UI branches on an as-needed basis.

**Comment by julien731** [comment]
Sounds good to me. We can then move this issue to https://github.com/burigems/buriauth
